import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 });
await page.goto('http://127.0.0.1:5173/about?v=' + Date.now(), { waitUntil: 'networkidle' });
await page.waitForTimeout(1000);
const footer = page.locator('footer').first();
await footer.scrollIntoViewIfNeeded();
await page.waitForTimeout(400);
await footer.screenshot({ path: 'tmp_check_footer_mobile_new.png' });
await browser.close();
